# Generated by Django 4.0 on 2022-01-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='400-200.png', upload_to='')),
                ('artist_bio', models.TextField()),
                ('genre', models.CharField(max_length=100)),
                ('year_of_inception', models.DateTimeField()),
                ('albums', models.TextField()),
                ('songs_trivia', models.TextField()),
                ('anniversary_date', models.CharField(max_length=50)),
                ('facebook_url', models.TextField()),
                ('instagram_url', models.TextField()),
            ],
        ),
    ]
