# Generated by Django 4.0 on 2022-01-05 16:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
