# Generated by Django 4.0 on 2022-01-06 04:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_alter_artist_artist_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='albums',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='songs_trivia',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
