# Generated by Django 4.0 on 2022-01-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_podcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radiolink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
            ],
        ),
    ]
